name: Generate Activity Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate activity graph
        uses: maurodesouza/github-readme-activity-graph-action@v1
        with:
          username: ilhomn
          options: "theme=tokyo-night&area=true&hide_border=true&bg_color=00000000"
          output_path: dist/activity-graph.svg
      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update activity graph"
          file_pattern: "dist/activity-graph.svg"
